apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-api
  namespace: argocd
spec: 
  project: default

  source: 
    repoURL: https://github.com/RavianXReaver/argocd-app-config.git
    targetRevision: HEAD
    path: staging
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true