apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-api-dev
  namespace: argocd
spec: 
  project: default

  source: 
    repoURL: https://github.com/RavianXReaver/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels: istio-injection=enabled

    automated: 
      selfHeal: true
      prune: true